import { contextBridge, ipcRenderer, webUtils } from 'electron';
import { CONTROLLER_FS_CHANNELS } from './controller-ipc-channels.mjs';

contextBridge.exposeInMainWorld('helloMisterDesktop', {
  appName: 'Hello Mister v2.1',
  safetyMode: 'dry-run',
  getRuntimeEnvironment: () => ipcRenderer.invoke('app:runtime-environment'),
  getAppDataStorageStatus: () => ipcRenderer.invoke('app:data-status'),
  openAppDataFolder: () => ipcRenderer.invoke('app:open-data-folder'),
  openExternalUrl: (url) => ipcRenderer.invoke('app:open-external', url),
  saveCardImage: (payload) => ipcRenderer.invoke('app:save-card-image', payload),
  listNetworkInterfaces: () => ipcRenderer.invoke('mister:list-network-interfaces'),
  scanMisterCandidates: (options) => ipcRenderer.invoke('mister:scan-candidates', options),
  probeMisterReachable: (host, port, timeoutMs) => ipcRenderer.invoke('mister:probe-reachable', { host, port, timeoutMs }),
  loadMisterProfiles: () => ipcRenderer.invoke('mister:profiles:load'),
  saveMisterProfile: (profile) => ipcRenderer.invoke('mister:profiles:save', profile),
  getActiveMisterProfile: () => ipcRenderer.invoke('mister:active-profile:get'),
  setActiveMisterProfile: (profile) => ipcRenderer.invoke('mister:active-profile:set', profile),
  clearActiveMisterProfile: (profileId) => ipcRenderer.invoke('mister:active-profile:clear', profileId),
  saveMisterProfilePassword: (profileId, password) => ipcRenderer.invoke('mister:profiles:password:save', { profileId, password }),
  getMisterProfilePasswordStatus: (profileId) => ipcRenderer.invoke('mister:profiles:password:status', { profileId }),
  deleteMisterProfilePassword: (profileId) => ipcRenderer.invoke('mister:profiles:password:delete', { profileId }),
  setDefaultMisterProfile: (profileId) => ipcRenderer.invoke('mister:profiles:set-default', profileId),
  deleteMisterProfile: (profileId, options) => ipcRenderer.invoke('mister:profiles:delete', { profileId, options }),
  loadMisterProfileSummaries: () => ipcRenderer.invoke('mister:profiles:summaries:load'),
  saveMisterProfileSummary: (summary) => ipcRenderer.invoke('mister:profiles:summaries:save', summary),
  clearMisterProfileSummary: (profileId) => ipcRenderer.invoke('mister:profiles:summaries:clear', profileId),
  zaparooGetStatus: (target) => ipcRenderer.invoke('zaparoo:status', { target }),
  zaparooGetVersion: (target) => ipcRenderer.invoke('zaparoo:version', { target }),
  zaparooHealth: (target) => ipcRenderer.invoke('zaparoo:health', { target }),
  zaparooSearchMedia: (request) => ipcRenderer.invoke('zaparoo:media-search', request),
  zaparooBrowseMedia: (request) => ipcRenderer.invoke('zaparoo:media-browse', request),
  zaparooLookupMedia: (request) => ipcRenderer.invoke('zaparoo:media-lookup', request),
  zaparooRun: (request) => ipcRenderer.invoke('zaparoo:run', request),
  zaparooListReaders: (target) => ipcRenderer.invoke('zaparoo:readers', { target }),
  zaparooWriteReader: (request) => ipcRenderer.invoke('zaparoo:readers-write', request),
  zaparooReadTokenOnce: (request) => ipcRenderer.invoke('zaparoo:token-read-once', request),
  zaparooCancelTokenRead: (requestId) => ipcRenderer.invoke('zaparoo:token-read-cancel', { requestId }),
  zaparooReadConfigDiagnostics: (sessionId) => ipcRenderer.invoke('zaparoo:config:diagnose', { sessionId }),
  zaparooPreviewConfigApply: (request) => ipcRenderer.invoke('zaparoo:config:preview-apply', request),
  zaparooApplyConfigRecommendation: (request) => ipcRenderer.invoke('zaparoo:config:apply', request),
  inspectSshHostKey: (request) => ipcRenderer.invoke('mister:ssh:inspect-host-key', request),
  trustSshHostKey: (request) => ipcRenderer.invoke('mister:ssh:trust-host-key', request),
  removeSshKnownHost: (host, port) => ipcRenderer.invoke('mister:ssh:remove-known-host', { host, port }),
  listSshKnownHosts: () => ipcRenderer.invoke('mister:ssh:list-known-hosts'),
  listSshKnownHostHistory: () => ipcRenderer.invoke('mister:ssh:list-known-host-history'),
  fingerprintMister: (credential) => ipcRenderer.invoke('mister:ssh:fingerprint', credential),
  fingerprintSavedMisterProfile: (request) => ipcRenderer.invoke('mister:ssh:fingerprint-profile', request),
  fingerprintMisterSession: (sessionId) => ipcRenderer.invoke('mister:ssh:fingerprint-session', sessionId),
  clearSshSession: (sessionId) => ipcRenderer.invoke('mister:ssh:clear-session', sessionId),
  listSshSessions: () => ipcRenderer.invoke('mister:ssh:list-sessions'),
  readRemoteMisterIni: (sessionId) => ipcRenderer.invoke('mister:remote:read-ini', sessionId),
  iniFsCheckWriteCapability: (request) => ipcRenderer.invoke('iniFs:checkWriteCapability', request),
  iniFsListRemoteIni: (request) => ipcRenderer.invoke('iniFs:listRemoteIni', request),
  iniFsReadRemoteIni: (request) => ipcRenderer.invoke('iniFs:readRemoteIni', request),
  iniFsWriteRemoteIniWithBackup: (request) => ipcRenderer.invoke('iniFs:writeRemoteIniWithBackup', request),
  iniFsCreateBackup: (request) => ipcRenderer.invoke('iniFs:createBackup', request),
  iniFsListBackups: (request) => ipcRenderer.invoke('iniFs:listBackups', request),
  iniFsPreviewBackup: (request) => ipcRenderer.invoke('iniFs:previewBackup', request),
  iniFsDeleteBackup: (request) => ipcRenderer.invoke('iniFs:deleteBackup', request),
  iniFsRestoreBackup: (request) => ipcRenderer.invoke('iniFs:restoreBackup', request),
  iniFsTrashIni: (request) => ipcRenderer.invoke('iniFs:trashIni', request),
  iniFsListTrash: (request) => ipcRenderer.invoke('iniFs:listTrash', request),
  iniFsRestoreTrashedIni: (request) => ipcRenderer.invoke('iniFs:restoreTrashedIni', request),
  iniFsDeleteTrashedIni: (request) => ipcRenderer.invoke('iniFs:deleteTrashedIni', request),
  iniFsEmptyTrash: (request) => ipcRenderer.invoke('iniFs:emptyTrash', request),
  iniFsExportIniLocal: (request) => ipcRenderer.invoke('iniFs:exportIniLocal', request),
  iniFsImportIniLocal: (request) => ipcRenderer.invoke('iniFs:importIniLocal', request),
  iniFsLoadMetadata: (request) => ipcRenderer.invoke('iniFs:metadata:load', request),
  iniFsSaveMetadata: (store) => ipcRenderer.invoke('iniFs:metadata:save', store),

  scriptFsCheckCapability: (request) => ipcRenderer.invoke('scriptFs:checkCapability', request),
  scriptFsListRemote: (request) => ipcRenderer.invoke('scriptFs:listRemote', request),
  scriptFsReadRemote: (request) => ipcRenderer.invoke('scriptFs:readRemote', request),
  scriptFsWriteRemote: (request) => ipcRenderer.invoke('scriptFs:writeRemote', request),
  scriptFsCreateBackup: (request) => ipcRenderer.invoke('scriptFs:createBackup', request),
  scriptFsListBackups: (request) => ipcRenderer.invoke('scriptFs:listBackups', request),
  scriptFsPreviewBackup: (request) => ipcRenderer.invoke('scriptFs:previewBackup', request),
  scriptFsRestoreBackup: (request) => ipcRenderer.invoke('scriptFs:restoreBackup', request),
  scriptFsDeleteBackup: (request) => ipcRenderer.invoke('scriptFs:deleteBackup', request),
  scriptFsTrash: (request) => ipcRenderer.invoke('scriptFs:trash', request),
  scriptFsListTrash: (request) => ipcRenderer.invoke('scriptFs:listTrash', request),
  scriptFsRestoreTrashed: (request) => ipcRenderer.invoke('scriptFs:restoreTrashed', request),
  scriptFsDeleteTrashed: (request) => ipcRenderer.invoke('scriptFs:deleteTrashed', request),
  scriptFsEmptyTrash: (request) => ipcRenderer.invoke('scriptFs:emptyTrash', request),
  scriptFsExportLocal: (request) => ipcRenderer.invoke('scriptFs:exportLocal', request),
  scriptFsImportLocal: (request) => ipcRenderer.invoke('scriptFs:importLocal', request),
  scriptFsRun: (request) => ipcRenderer.invoke('scriptFs:run', request),
  scriptFsReadRunLog: (request) => ipcRenderer.invoke('scriptFs:readRunLog', request),
  scriptFsCopyToDevice: (request) => ipcRenderer.invoke('scriptFs:copyToDevice', request),
  scriptFsInstallFromUrl: (request) => ipcRenderer.invoke('scriptFs:installFromUrl', request),
  onScriptRunChunk: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on('scriptFs:run:chunk', handler);
    return () => ipcRenderer.removeListener('scriptFs:run:chunk', handler);
  },
  onScriptRunDone: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on('scriptFs:run:done', handler);
    return () => ipcRenderer.removeListener('scriptFs:run:done', handler);
  },
  controllerFsScanInventory: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.scanInventory, request),
  controllerFsReadFile: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.readFile, request),
  controllerFsReadControllerFile: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.readControllerFile, request),
  controllerFsCreateBackup: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.createBackup, request),
  controllerFsListBackups: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.listBackups, request),
  controllerFsReadBackup: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.readBackup, request),
  controllerFsRestoreBackup: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.restoreBackup, request),
  controllerFsListConnectedDevices: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.listConnectedDevices, request),
  controllerFsReadInputCaps: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.readInputCaps, request),
  controllerFsCloneMappings: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.cloneMappings, request),
  controllerFsAutoMap: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.autoMap, request),
  controllerFsStartInputMonitor: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.startInputMonitor, request),
  controllerFsStopInputMonitor: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.stopInputMonitor, request),
  controllerFsListMaps: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.listMaps, request),
  controllerFsReadMap: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.readMap, request),
  controllerFsReadAllMaps: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.readAllMaps, request),
  controllerFsWriteMap: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.writeMap, request),
  controllerFsWriteMaps: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.writeMaps, request),
  controllerFsReadArcadeButtons: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.readArcadeButtons, request),
  controllerFsReadArcadeIndex: (request) => ipcRenderer.invoke(CONTROLLER_FS_CHANNELS.readArcadeIndex, request),
  onControllerInputEvent: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on('controllerFs:input:event', handler);
    return () => ipcRenderer.removeListener('controllerFs:input:event', handler);
  },
  listRemoteGames: (sessionId, options) => ipcRenderer.invoke('mister:remote:list-games', sessionId, options),
  listRemoteGameFolderFiles: (sessionId, folderPath, options) => ipcRenderer.invoke('mister:remote:list-game-folder-files', { sessionId, folderPath, options }),
  listRemoteGameFilesFast: (sessionId) => ipcRenderer.invoke('mister:remote:list-game-files-fast', { sessionId }),
  listRemoteArcadeCores: (sessionId) => ipcRenderer.invoke('mister:remote:list-arcade-cores', { sessionId }),
  listRemoteScripts: (sessionId) => ipcRenderer.invoke('mister:remote:list-scripts', sessionId),
  readRemoteScript: (sessionId, path) => ipcRenderer.invoke('mister:remote:read-script', { sessionId, path }),
  saveDiagnosticPackage: (diagnostic) => ipcRenderer.invoke('diagnostics:save-package', diagnostic),
  listWindowsDrives: () => ipcRenderer.invoke('sd:list-drives'),
  inspectSdStructure: (mountPoint, driveId) => ipcRenderer.invoke('sd:inspect-structure', { mountPoint, driveId }),
  selectMrFusionImage: () => ipcRenderer.invoke('file:select-mr-fusion-image'),
  resolveMrFusionImage: (options) => ipcRenderer.invoke('sd:resolve-mr-fusion', options),
  downloadMrFusionImage: (options) => ipcRenderer.invoke('sd:download-mr-fusion', options),
  onSdDownloadProgress: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on('sd:download:progress', handler);
    return () => ipcRenderer.removeListener('sd:download:progress', handler);
  },
  flashSdImage: (request) => ipcRenderer.invoke('sd:flash-image', request),
  onSdFlashProgress: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on('sd:flash:progress', handler);
    return () => ipcRenderer.removeListener('sd:flash:progress', handler);
  },
  writeWpaSupplicant: (request) => ipcRenderer.invoke('sd:write-wpa-supplicant', request),
  writeMisterIni: (request) => ipcRenderer.invoke('sd:write-mister-ini', request),
  installMisterScriptToCard: (request) => ipcRenderer.invoke('sd:install-mister-script', request),
  installZaparooToCard: (request) => ipcRenderer.invoke('sd:install-zaparoo', request),
  onSdScriptProgress: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on('sd:script:progress', handler);
    return () => ipcRenderer.removeListener('sd:script:progress', handler);
  },
  ejectSdDrive: (request) => ipcRenderer.invoke('sd:eject-drive', request),
  scanWifiNetworks: () => ipcRenderer.invoke('sd:scan-wifi-networks'),
  selectLocalRomFiles: () => ipcRenderer.invoke('rom:select-files'),
  selectLocalRomFolder: (options) => ipcRenderer.invoke('rom:select-folder', options),
  selectRomBackupFolder: () => ipcRenderer.invoke('rom:select-backup-folder'),
  romFsListRemote: (request) => ipcRenderer.invoke('romFs:listRemote', request),
  romFsStatRemote: (request) => ipcRenderer.invoke('romFs:statRemote', request),
  romFsCheckCapability: (request) => ipcRenderer.invoke('romFs:checkCapability', request),
  romFsSelectLocalFolder: () => ipcRenderer.invoke('romFs:selectLocalFolder'),
  romFsListLocalFolder: (request) => ipcRenderer.invoke('romFs:listLocalFolder', request),
  romFsListLocalTreeRoots: () => ipcRenderer.invoke('romFs:listLocalTreeRoots'),
  romFsListLocalTreeFolder: (request) => ipcRenderer.invoke('romFs:listLocalTreeFolder', request),
  romFsCopyLocalToMister: (request) => ipcRenderer.invoke('romFs:copyLocalToMister', request),
  romFsCopyMisterToLocal: (request) => ipcRenderer.invoke('romFs:copyMisterToLocal', request),
  romFsCopyMisterToMister: (request) => ipcRenderer.invoke('romFs:copyMisterToMister', request),
  romFsMoveRemote: (request) => ipcRenderer.invoke('romFs:moveRemote', request),
  romFsRenameRemote: (request) => ipcRenderer.invoke('romFs:renameRemote', request),
  romFsTrashRemote: (request) => ipcRenderer.invoke('romFs:trashRemote', request),
  romFsDeleteRemote: (request) => ipcRenderer.invoke('romFs:deleteRemote', request),
  romFsRestoreRemote: (request) => ipcRenderer.invoke('romFs:restoreRemote', request),
  romFsCreateRemoteFolder: (request) => ipcRenderer.invoke('romFs:createRemoteFolder', request),
  romFsCreateLocalFolder: (request) => ipcRenderer.invoke('romFs:createLocalFolder', request),
  selectStickerImageFiles: () => ipcRenderer.invoke('stickers:select-image-files'),
  selectStickerImageFolder: (options) => ipcRenderer.invoke('stickers:select-image-folder', options),
  loadStickerImageLibrary: () => ipcRenderer.invoke('stickers:images:load'),
  saveStickerImageLibrary: (store) => ipcRenderer.invoke('stickers:images:save', store),
  loadStickerTemplates: () => ipcRenderer.invoke('stickers:templates:load'),
  saveStickerTemplates: (store) => ipcRenderer.invoke('stickers:templates:save', store),
  loadStickerCards: () => ipcRenderer.invoke('stickers:cards:load'),
  saveStickerCards: (store) => ipcRenderer.invoke('stickers:cards:save', store),
  loadStickerSheets: () => ipcRenderer.invoke('stickers:sheets:load'),
  saveStickerSheets: (store) => ipcRenderer.invoke('stickers:sheets:save', store),
  loadSavedRomPlans: () => ipcRenderer.invoke('rom:plans:load'),
  saveSavedRomPlan: (plan) => ipcRenderer.invoke('rom:plans:save', plan),
  deleteSavedRomPlan: (planId) => ipcRenderer.invoke('rom:plans:delete', planId),
  calculateFileSha256: (filePath) => ipcRenderer.invoke('file:sha256', filePath),
  saveTextFile: (options) => ipcRenderer.invoke('file:save-text', options),
  loadTaskLogs: () => ipcRenderer.invoke('tasks:load'),
  saveTaskLogs: (tasks) => ipcRenderer.invoke('tasks:save', tasks),
  clearTaskLogs: () => ipcRenderer.invoke('tasks:clear'),
  exportTaskLogs: (tasks) => ipcRenderer.invoke('tasks:export', tasks),
});

contextBridge.exposeInMainWorld('zaparooDesktop', {
  bridgeUrl: 'http://127.0.0.1:37321',
  saveAndOpenPdf: (bytes, filename) => ipcRenderer.invoke('zaparoo:save-and-open-pdf', { bytes, filename }),
  saveFile: (bytes, filename, mimeType) => ipcRenderer.invoke('zaparoo:save-file', { bytes, filename, mimeType }),
  openFile: (filePath) => ipcRenderer.invoke('zaparoo:open-file', { filePath }),
  captureHtmlAsPng: (html, width, height) => ipcRenderer.invoke('zaparoo:capture-html-png', { html, width, height }),
  readFileAsDataUrl: (filePath) => ipcRenderer.invoke('zaparoo:read-file-data-url', { filePath }),
  fetchImageAsDataUrl: (url) => ipcRenderer.invoke('zaparoo:fetch-image-data-url', { url }),
  getPathForFile: (file) => {
    try {
      return webUtils.getPathForFile(file);
    } catch {
      return undefined;
    }
  },
});
